name: job_portal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  lottie: ^3.3.1
  intl: ^0.20.2
  provider: ^6.0.5
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  http: ^1.2.2
  firebase_storage: ^13.0.2
  firebase_auth: ^6.1.0
  google_fonts: any
  web: ^1.1.1
  flutter_svg: ^2.0.17
  another_flushbar: ^1.12.30
  go_router: ^16.2.4
  pdf: ^3.10.4
  timeago: ^3.3.0
  cached_network_image: ^3.4.1
  fl_chart: ^1.0.0
  flutter_date_pickers: ^0.4.3
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  read_pdf_text: ^0.3.1
  markdown_widget: ^2.3.2+8
  printing: ^5.14.2
  image_picker_for_web: ^3.1.0
  image_picker: ^1.2.0
  flutter_dotenv: ^6.0.0
  file_picker: ^10.3.3
  mime: ^2.0.0
  font_awesome_flutter: ^10.12.0
  syncfusion_flutter_charts: ^32.1.21
  tuple: any



  archive: any
  xml: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ai.json
    - images/
    - images/anim.json
    - images/logo.png
    - images/splash.webp
    - images/signup_recruiter.svg
    - images/signup_jobseeker.svg
    - images/login_recruiter.svg
    - images/login_jobseeker.svg
    - images/forgot.svg
    - images/recruiter_2.svg
    - images/success.json
    - images/MaterialIcons-Regular.ttf
    - images/1.json
    - images/2.json
    - images/3.json
    - images/4.json
